[package]
name = "tumor_model"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.3"
ndarray-stats = "0.5.0"
ndrustfft = "0.2.0"
rand = "0.8.4"
